-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 13:52:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `department_no` INT NOT NULL,
  `department_name` VARCHAR(45) NULL,
  `department_address` VARCHAR(45) NULL,
  PRIMARY KEY (`department_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_no` INT NOT NULL,
  `employee_name` VARCHAR(45) NULL,
  `department_no` INT NOT NULL,
  PRIMARY KEY (`employee_no`),
  INDEX `fk_employee_department1_idx` (`department_no` ASC) VISIBLE,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_no`)
    REFERENCES `mydb`.`department` (`department_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `skill_code` INT NOT NULL,
  `skill_type` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `project_code` INT NOT NULL,
  `project_title` VARCHAR(45) NULL,
  `project_manager` INT NOT NULL,
  `project_budget` DECIMAL NULL,
  PRIMARY KEY (`project_code`),
  INDEX `project_manager_idx` (`project_manager` ASC) VISIBLE,
  CONSTRAINT `project_manager`
    FOREIGN KEY (`project_manager`)
    REFERENCES `mydb`.`employee` (`employee_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_skill` (
  `employee_no` INT NOT NULL,
  `skill_code` INT NOT NULL,
  `skill_level` INT NULL,
  PRIMARY KEY (`employee_no`, `skill_code`),
  INDEX `fk_employee_has_skill_skill1_idx` (`skill_code` ASC) VISIBLE,
  INDEX `fk_employee_has_skill_employee_idx` (`employee_no` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_skill_employee`
    FOREIGN KEY (`employee_no`)
    REFERENCES `mydb`.`employee` (`employee_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_skill_skill1`
    FOREIGN KEY (`skill_code`)
    REFERENCES `mydb`.`skill` (`skill_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`project_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project_employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project_employee` (
  `employee_no` INT NOT NULL,
  `project_code` INT NOT NULL,
  `hourly_rate` INT NULL,
  PRIMARY KEY (`employee_no`, `project_code`),
  INDEX `fk_employee_has_project_project1_idx` (`project_code` ASC) VISIBLE,
  INDEX `fk_employee_has_project_employee1_idx` (`employee_no` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_project_employee1`
    FOREIGN KEY (`employee_no`)
    REFERENCES `mydb`.`employee` (`employee_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_project_project1`
    FOREIGN KEY (`project_code`)
    REFERENCES `mydb`.`project` (`project_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

desc mydb.department;
desc mydb.employee;
desc mydb.project;
desc mydb.skill;
desc mydb.project_employee;
desc mydb.employee_skill;
